### PR TITLE
package name is `soyuka/contexts`

### PR DESCRIPTION
**Pull request by jdeniau**
| Q             | A
| ------------- | ---
| Branch?       | main
| Bug fix?      | no 
| New feature?  | no 
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by MirakuSan** [comment]
Maybe you can also change all namespace ? 

Example : `namespace Behatch\Context;` becomes `namespace Soyuka\Context;`
What do you think?

**Comment by jdeniau** [comment]
It seems interesting for the next major release, but it's a way bigger change and will need a separate PR.
You may want to open an RFC issue about this.

**Comment by MirakuSan** [comment]
It seems the repo is not open for adding issues, @soyuka can you create an issue for the namespace or change the repository parameters so I can do it ?

**Comment by francisbesset** [comment]
If the namespace change, also soyuka/contexts cannot be keep the [replace sanpi/behatch-contexts](https://github.com/soyuka/contexts/blob/89c831e39355d646a4d141e9c9051323f27de8fb/composer.json#L37), or use [class_alias](https://www.php.net/manual/en/function.class-alias.php)() to keep backward compatibility.

**Comment by soyuka** [comment]
it's such a pain changing a namespace in PHP. IMO this is a no-go, I've talked with other maintainers and ppl that use behat, we maintain this because we need it but I'd like it to just stay a "maintained fork" and not really add new features, fix people issues etc. so not really up to opening issues here.

**Pull request merged**
