### PR TITLE
chore: add testruns for php 8.3

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by Jean-Beru** [comment]
Thanks for your PR @Chris53897, can you fix coding style too?

**Comment by Chris53897** [comment]
Of course i can do that. But in a seperate PR.
This is not related to this PR.

**Comment by Jean-Beru** [comment]
Much better. Thank you.

**Comment by Chris53897** [comment]
https://github.com/soyuka/contexts/pull/30

**Comment by soyuka** [comment]
Let's see and probably fix issues in another patch

**Pull request merged**
