### PR TITLE
increase JSON context DX

### PR DESCRIPTION
**Pull request by jdeniau**
| Q             | A
| ------------- | ---
| Branch?       | main
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

Thanks for the effort of forking behatch/contexts.

As behatch/context is unmaintained, I open the same PR [I did there](https://github.com/Behatch/contexts/pull/262).

This pull request improves the error message, by telling which node is failing, the actual content and the expected value.

For the record, we use this at Mapado on [my fork](https://github.com/jdeniau/contexts) since 2018, and we find it way better with those messages.

Before (fail on first error, no hint about which line does fail):
image

With PR:
image

### CODE REVIEW

**Comment by soyuka** [comment]
damn we should use a github actions ci if we really want to maintain this, did you run the tests?

**Comment by jdeniau** [comment]
Woops I did not saw that there was a Travis CI!

I just copied my PR on behatch here. 

I will look at this maybe tomorrow!

**Comment by jdeniau** [comment]
@soyuka OK I understand your message now ! The `main` branch is failing too due to selenium.

This PR is a clone of https://github.com/Behatch/contexts/pull/262 , where the CI did pass.
For the record, we use this since 2018 on [Mapado](https://github.com/mapado) code base ([more than 100 000 lines of behat tests](https://pro.mapado.com/join-the-team/dev-php-symfony-le-plus/)), so I'm pretty confidant about it 🫡

It seems that your fork did not change that much, so CI should pass 🤞 . If you want to merge this, and the CI does fail after fixing selenium, ping me and I will correct it if you want.

**Comment by soyuka** [comment]
I'll move the CI at some point

**Comment by soyuka** [comment]
actually: https://github.com/soyuka/contexts/pull/2 haha need to make this work

**Pull request merged**
